zeus-api-gateway:
  api:
    version: 1.0.0
server:
  port: 8088
spring:
  profiles:
    active: local, clean
  security:
    user:
      name: user
      password: user
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:gatewaydb
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true