zeus-api-gateway:
  api:
    version: 1.0.0
url:
  host:
    trading-partner: http://localhost:8081/api/v1/
    ref-data: http://localhost:8080/api/v1/
    member-mgmt: http://localhost:8084/api/v1/
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apigatewaydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: apigatewayapp
    password: password
  profiles:
    active: local, clean
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:gatewaydb
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: apigatewayadmin
    password: password
    clean-disabled: false
logging:
  file:
    name: logs/local/tp.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace